from transformers import pipeline

def generate_feedback(stroke_data):
    """
    Generate biomechanically grounded feedback for the given stroke data using a large language model (LLM).
    
    Parameters:
    stroke_data (dict): A dictionary containing relevant features of the stroke for analysis.
    
    Returns:
    str: Feedback generated by the LLM.
    """
    # Initialize the LLM pipeline
    llm = pipeline("text-generation", model="gpt2")  # Replace with the appropriate model

    # Format the input for the LLM
    input_text = format_input_for_llm(stroke_data)

    # Generate feedback
    feedback = llm(input_text, max_length=150)[0]['generated_text']

    return feedback


def format_input_for_llm(stroke_data):
    """
    Format the stroke data into a string suitable for LLM input.
    
    Parameters:
    stroke_data (dict): A dictionary containing relevant features of the stroke for analysis.
    
    Returns:
    str: Formatted input string for the LLM.
    """
    formatted_input = "You're a professional tennis coach reviewing a player's stroke. Based on the following biomechanical and classification data, provide specific, constructive feedback on technique, performance quality, areas for improvement, and any potential injury risks:\n"
    for key, value in stroke_data.items():
        formatted_input += f"{key}: {value}\n"
    
    return formatted_input.strip()