[project]
name = "nyx-eama"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "ezc3d>=1.5.19",
    "pandas>=2.3.1",
    "requests>=2.32.4",
]
